### ISSUE TITLE
Python 3 all the things...

### ISSUE THREAD

**Issue by ntoll** [ricmoo/pyscrypt#2]
Hi,

I'd like to use this in a Python 3 project. I notice that your pyaes is Py3 friendly but not this one. AFAICT there are a couple of exception syntax errors (i.e. use `except Exception as e:` syntax) and old school print statements. I'm guessing bytes / strings in Py3 might also cause issues.

Happy to help if need be.

N.

**Comment by ricmoo** [comment]
Hey ntoll,

It's something I've been planning for quite some time, and I have a half-complete Python 3 friendly version done. The largest problem by far is the bytes/strings handling. I will try to get it complete and pushed by end of day tomorrow (January 21st, 2014).

I don't do much with Python 3, so I largely trust my test cases to ensure it works, but any help testing once I post it would be greatly appreciated. :)

Thanks,
RicMoo

**Comment by ntoll** [comment]
Great stuff... I'll pause my work on this since you know your way around the code and I'm nervous of 2to3 ;-)

Happy to help in any way that I can.

**Comment by ricmoo** [comment]
Heya!

I have updated the library, and all the test cases pass, but a little extra testing won't hurt. Please give it a try and let me know. If there are no issues, I'll tag the release tomorrow afternoon and sdist upload 1.6 to pypi.

If interested, take a look at the change... There were lots of little things along the way. :)

https://github.com/ricmoo/pyscrypt/commit/d38f81fcfab888f212684d759e59afd0bba1ebd3
